### ISSUE TITLE
Add sound to this sim

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#181]
At the sound design meeting we realized we need a more slider-y sound for GFL regular as the mass control is a continuous slider with a tweaker.

**Ideas & decisions:**
- Let's try the sound in Basics but limit the frequency at which it can be played
- At the max min values add an effect to indicate the end
- The range of the mass sound and the force sound will need to be adjusted for this sim as the ranges are greater than in Basics.
- Agreed we would start with the sounds from Basics and go from there.

**Comment by Ashton-Morris** [comment]
**Ideas & decisions:**

- We will start with the GFL:B Mass sound and choose a pleasant repetition interval for when the slider is being dragged. 
- When the arrow buttons for Mass are pressed we will trigger one Mass sound
- We will map it to pitch and experiment with what range sounds best
- We will also try adding reverb to the smallest and largest mass option in order to audibly acknowledge the boundaries of the mass slider.

**Comment by terracoda** [comment]
@Ashton-Morris, in case you need to know:
-  range 10 kg to 1000
- default step with keyboard 50 kg
- larger step with pg up and page down is 100 kg
- smallest step with keyboard is 1 kg
- can jump to 10 kg with Home key
- can jump to 1000 kg with End Key

**Comment by jbphet** [comment]
@terracoda, @emily-phet, @terracoda and I reviewed the latest version of the sound implementation today and concluded that the force sounds and the boundary sounds are in good shape at this point.  The mass sound generator should be changed to play sounds for discrete values, similar to what is done in Resistance in a Wire, when the user is changing the value via the slider, but otherwise the current behavior is not too bad.  I'll implement that and publish a dev version for review.

**Comment by jbphet** [comment]
@terracoda, @Ashton-Morris, and @emily-phet - I've published a version for review the includes discrete increments for the mass sounds when the slider is dragged, decent handling for keyboard-based changes, and common UI sounds.  Please review and provide your feedback.

https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.19/phet/gravity-force-lab_en_phet.html?supportsSound

**Comment by jbphet** [comment]
One thing I noticed when playing around with it is that we don't have pickup and release sounds for the ruler.  I'm thinking I should add them.  How about I use the same ones that we used in Friction in the magnifier view?

**Comment by emily-phet** [comment]
@jbphet - Sure, let's see how that feels with the other sounds.

**Comment by terracoda** [comment]
@jbphet, and @emily-phet, there are also 2 custom jump hotkeys for ruler:
- J + C to jump zero mark to center of m1
- J + H to release ruler and arrange it back in home position

I don't know if these "jumps" need sounds. 

In fact, I haven't thought about sonification for the ruler (apologies). It's use is non-essential for non-visual users, so I just wasn't thinking about it.  A lot of sims have rulers...there might something we can do with rulers in general or for general types of rulers. Maybe, too late for the imminent publication of this sim, but I'll open an issue for this, just in case.

**Comment by Ashton-Morris** [comment]
I did now know you could even pick up the ruler until reading this. I think the common UI pickup + release would fit here.

I think the amount that the mass plays on the slider is a good amount.

The only issue I have is that I can still hear a slight clipping when only messing with the back distance/force. I feel like we had this issue last time with the same sound and am not sure what we did to correct for it.

**Comment by jbphet** [comment]
I don't know why this didn't strike me before, but it seems a little odd that for higher force we use a higher pitched sound, but for higher mass we use a **lower** pitched sound.  In https://github.com/phetsims/molarity/issues/159 we reversed the pitch mapping of the concentration sound to be more consistent with the behavior of the precipitate sound.  Should we consider doing that here too?  Note that if we decide to change the behavior, we'll need to do the same in Gravity Force Lab Basics, which has already been published.

**Comment by jbphet** [comment]
I've published a dev version for review and for use in interviews, please see https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.23/phet/gravity-force-lab_en_phet.html?supportsSound&supportsEnhancedSound.  @Ashton-Morris, @emily-phet, and @terracoda - please review and let me know if you think anything should change.  Please think about my question in https://github.com/phetsims/gravity-force-lab/issues/181#issuecomment-566785448 and chime in with your opinion.

**Comment by terracoda** [comment]
@jbphet, this sounds great to me. This dev link does not contain all description for the ruler. That said, I think this will sound nice when all description is implemented.

**Comment by emily-phet** [comment]
Thoughts:

- Mass sliders - I'm not sure how I feel about hearing the rubbery thud sound when 'constant size' is checked. 
- Mass sliders - When moving the slider slowly with a mouse, It feels a little 'off' to me to hear discrete rubbery thud sounds. It's not an issue when I'm moving quickly and hearing some thud sounds as I go, but it feels weird to be able to move 20-30+ kg without hearing anything. I'm not sure why this didn't feel 'off' to me before, but I have some ideas for that which will come up in discussion next week.

Considering the needed timeline for this sim - what do folks think about restricting the mass slider rubbery thud to only when navigating with keyboard focus, and removing the rubbery sound altogether when "constant size" is checked. 

Ultimately, I think the challenges with the mass slider sound is an artifact (and on me) of us not tackling this sim like it's own independent sim. I think these issues would have stood out to us differently if we had done that, rather than approaching this as a GFL:B + a few differences. 

Regarding the high/low pitch mappings - I think the high pitch = larger mass really needs to be the mapping for those sliders. Switching the mapping for the force is an option, but I would prefer to avoid doing that unless is it very quick and straightforward.

**Comment by terracoda** [comment]
@emily-phet, are you suggesting these changes be the same on both the GFL and GFLB?

**Comment by emily-phet** [comment]
@terracoda I'm suggesting (strongly), only the changes regarding the mass slider, which doesn't apply to GFLB (which has number pickers, or whatever they're called). 

I'd like to avoid any changes related to the force sound (reversing mapping), which would have to implemented, tried out, decided upon (and if decided to keep, propagated to GFLB).

**Comment by terracoda** [comment]
@emily-phet, just to be clear, by "rubbery thud sound", you mean the "rubbery thud" or rubber band sound indicating a change in mass. It's current mapping is when mass gets bigger the pitch gets lower. AND not the rubbery bouncy bump sound that indicates meeting up with the other sphere on the track.

I am pretty sure you mean the former - the sound for mass in kilograms.
Current mapping is that the bigger the mass the lower the tone. This seems like the correct mapping to me.

**Considering other sims:**
- RIAW, more resistance = lower tone
- Molarity, more concentrated = lower tone
- Friction (more complicated, volume and tone), more jiggling = more volume, and I am not sure 100% sure about the tone for this sim, though a breakaway of the particles is a high pitch. To me volume seems to be the main indicator.

**Whereas in GFL and GFLB** 
- less distance > more force = higher tone
- more mass > more force = lower tone for mass and higher tone for force

In this sim, there was a decision to sonify mass changes and not sonify distance changes. I have a feeling that this may have been our critical error, not the actual sound for changes in mass in kg.

If we do not want to reverse the mapping for the force, I would suggest a safer route would be to simplify the sound design, and remove the mass sound all together (both for Constant size unchecked and checked). And perhaps, do this for both sims.

**My reasoning is about the learning goals:**
1. Distance has an inverse relationship with the force
2. Mass has a direct relationship with the force

If we remove the mass sound all together, there are no longer a conflicting mapping between mass and force, and the learners are free to interpret the relationships between the sound and changing distance and the sound and changing mass.

**Comment by emily-phet** [comment]
@terracoda Thanks for the detailed thoughts.

Are there any further thoughts or objections to removing the mass sound entirely for GFL(reg)? If there are no objections (though, please do share any you have!) that seems like the simplest path forward for now. The one loss that comes to my mind is that "feel" or presence of the spheres is lost from the non-visual experience. I always liked that physical cue of a hard rubber ball/sphere, particularly, for the non-visual learning experience.

Note - whatever we choose on this, I don't think that necessarily means we would have to do the same for GFLB. The number spinner setup is quite different than a slider, and considering that sim is targeting a younger age group, the sound also provides another (strong) cue to attend to the changing size of the spheres as the number spinner is used.

**Comment by Ashton-Morris** [comment]
Pedagogically it might make sense for the mapping to change but for intelligibility I think that having one tone go up (Force) while the other sound goes down (Mass) makes it easier to pickup on audibly speaking. If they were both going up and down together I feel like it would stand out less.

I do think the constant size sound feels weird, but maybe we could take one of those sounds and make them denser sounding?

@emily-phet  "Mass sliders - When moving the slider slowly with a mouse" For some reason that doesn't stand out as an issue for me. It feels pretty natural to only hear it after a bit, but that could be because I am thinking visually too.

@terracoda I aesthetically like the mass sounds and how cohesive it makes the whole sim feel. I would defer to everyone else's opinion on wether it should stay in or not though. I guess I am just confused on why we had no issue with the other sim with very similar dynamics and were comfortable with the sound being in but not this one?

**Comment by terracoda** [comment]
@Ashton-Morris, your points are very well articulated. I agree with both. The sound with the mouse seems fine to me. I also like the current mass sound and think the mapping is good.

You point out that having a reverse mapping for force makes the sounds easier to hear and discern. That's an excellent point.

**Comment by jbphet** [comment]
We discussed the future of the mass sound in a review meeting today, and decided to do some quick-and-dirty interviewing on versions that include and exclude the mass sound.  Below are the links for this.

Note that I've turned on sound in the `package.json` file, so query parameters are no longer needed to enable sound.  

+ Without mass sounds: https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.26/phet/gravity-force-lab_en_phet.html
+ With mass sounds: https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.27/phet/gravity-force-lab_en_phet.html

**Comment by BLFiedler** [comment]
@emily-phet and I did some "guerilla interviews" in the lobby of Duane. I will report out at GFL sound meeting on Tuesday.

A note from Wanda: She found the simultaneous noise of the mass clicks and force tone distracting through my interaction and description, but she wants to play with the sim itself in a11y mode.

**Comment by BLFiedler** [comment]
@terracoda mentioned that there was talk of having edge sound for the mass sliders? Was there intention to add this, @jbphet ?

**Comment by jbphet** [comment]
> Was there intention to add this, @jbphet?

I believe we decided to interview on having the mass sounds either completely on or completely off, and it was an easier thing to do quickly.  It is certainly possible to have the edge sounds if we want them for the final version.  @terracoda - do you have a recommendation on this?

**Comment by emily-phet** [comment]
@terracoda @jbphet @Ashton-Morris @BLFiedler @zepumph 
As we discussed last week, I won't be attending the GFL meeting in the morning. Instead, here's my 2 cents regarding the mass slider sound. 

From the informal user testing I did, one thing stood out to me as most significant. At least one user (using the *with mass sound* version) interpreted the force sound as being a completely different sound when hearing it while interacting with the mass sliders than when hearing it as she moved the spheres. She did not interpret it as force sound and mass sound - rather as a different single sound that played as she moved the mass sliders, distinct from the single sound she heard while moving the spheres. This user was very attentive, and of the people I spoke with, I was most surprised by her interpretation.

While watching a different user use the version *without* the mass sound, it did seem to highlight more clearly that the main focus to attend to was how what you were changing (either the location of the spheres, or the mass of the spheres) impacted the force...akin to RIAW and OL. 

Based on this, my recommendation would be to either:
1) publish with no mass sound, or
2) publish with mass sound as an enhanced sound

Regarding the mass sound as a boundary sound - I have no preference or recommendation, but I would encourage you to make a final decision on this tomorrow to give @jbphet a chance to implement before his trip.

**Comment by terracoda** [comment]
Thanks for these notes Emily.
This is helpful!
Taliesin

**Comment by terracoda** [comment]
I personally feel that if we leave the mass sound in as an enhanced sound, we will be able to get continued feedback on sound combinations - that might be a nice (and potentially informative) path forward.

**Comment by terracoda** [comment]
Decision: We move Mass sound to enhanced and do not add edge sounds to regular sliders for now.

**Comment by jbphet** [comment]
I have made the following changes to the sound design implementation: 

+ Moved the mass sound to "enhanced"
+ Added sounds for dialog open/close (and removed the default close button sound)
+ Adjusted sound levels based on input from @Ashton-Morris 

@Ashton-Morris, @emily-phet, and @terracoda - please review and let me know if other changes are needed.

@zepumph - I'm adding you as an assignee so that you can track progress on this and see if there are any further changes desired that could block publication.

**Comment by Ashton-Morris** [comment]
I don't think any changes are needed. It sounds good.

**Comment by terracoda** [comment]
The sounds sound good to me.
I am no longer getting sounds on my iphone when I have VoiceOver on. I must have done something to my settings. The sounds work fine on iphone when VO is off.

This is also a problem for other sims - not just GFL, so I know it is a setting on my phone. I will keep playing with my settings, and once in RC, QA can make sure sound works with their settings.

**Comment by terracoda** [comment]
I lied, for Molarity, sound is working fine when I use VO on my iphone.
I will test again in the morning and make sure I have the correct parameters.

**Comment by terracoda** [comment]
Ok, it seems to be a VO problem. The sounds just stops sometimes. Re-loading seems to get around this problem.

The sounds and the enhanced sounds sound good to me.

**Comment by terracoda** [comment]
Noticed I am not getting ruler drag responses on mobile. I will open a new issue for that.

**Comment by zepumph** [comment]
Ok, it sounds like things have solidified here. I'm going to close and move to an RC in #232. We can always make future tweaks if anyone needs to. Closing
