### ISSUE TITLE
Ruler only moves 1/2 of the time

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#189]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/455
When trying to drag the ruler, either with a mouse or touch screen it only grabs on every other time.

**Visuals**
![rulerwontdrag](https://user-images.githubusercontent.com/41024075/68431578-c6692a80-016f-11ea-9c78-87886f7ad116.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity Force Lab‬
URL: https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.16/phet/gravity-force-lab_all_phet.html?showPointerAreas
Version: 2.2.0-dev.16 2019-11-06 21:45:42 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Not restricted by platform

**Comment by KatieWoe** [comment]
a11y view may give hint as to what is happening:
![behavea11y](https://user-images.githubusercontent.com/41024075/68495435-67f28980-020d-11ea-88aa-7b04f5d01a06.gif)

**Comment by KatieWoe** [comment]
![behavea11y2](https://user-images.githubusercontent.com/41024075/68496104-cec47280-020e-11ea-8847-b0f6be20dafa.gif)

**Comment by zepumph** [comment]
This is happening because we added `this.node.interruptInput()` as part of the `baseInteractionUpdate`. This was added for a reason relating to the keyboard drag listener. I can't exactly remember. @jessegreenberg can we talk about this together tomorrow. It isn't obvious to me currently how we will support the cross product of device listeners support (mouse/keyboard/gesture) and features (alerts/pdom updates). Right now it doesn't seem like they can all exist together.

**Comment by zepumph** [comment]
The interrupt line was added over in https://github.com/phetsims/gravity-force-lab/issues/186.

**Comment by zepumph** [comment]
We found that this isn't happening for BASE because the pointer listener is added to the parent of the Node that gets the grab/drag interaction.

**Comment by zepumph** [comment]
The issue here is that we were interrupting all listeners on the Node. GrabDragInteraction shouldn't be able to interrupt everything, only the listeners that were going to be removed when converting to/from grabbable/draggable. The change was implemented above, and this bug has been fixed. Thanks @jessegreenberg for the idea!

**Comment by zepumph** [comment]
I'm going to close this issue.
