### ISSUE TITLE
Ruler not released on touch when focus is moved away from it

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#201]
This may be related to #194 and other recent issues about the ruler interaction.

I just noticed on 
https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.16/phet/gravity-force-lab_en_phet.html

That the ruler doesn't seem to get released and thus I am not able to regrab it. Maybe this is already known and this a redundant issue. 

Doing no further testing on mobile until you give me a new dev version @zepumph

**Comment by zepumph** [comment]
@terracoda, the above commit was worked on as part of #194, but @jessegreenberg and I think it may effect this issue. Has this been fixed?

**Comment by terracoda** [comment]
@zepumph, the ruler was successfully released a couple of times, and I heard the appropriate response a couple of times, but there are still  issues. 

- I don't always hear "Released" when I lift my finger
- I don't always hear the associated grab alerts and release alerts
- the VO highlight is sometimes not around the ruler when cycle back through items looking to grab it again

I am also having a lot of trouble reading through the sim content with cursor gestures (up and down to go to headings; left and right to read line by line). It is easy for me to get skip sections or get stuck on elements.

This could be due the small space for swiping. It could be because I haven't been using VO gestures for very long. Or it could be we have some issues to the way things are layered in accessible PDOM. I am not sure what is happening.

**Comment by terracoda** [comment]
I might need to call in some help from an expert gesture VO user.

**Comment by terracoda** [comment]
@zepumph I was testing dev 18 in https://github.com/phetsims/gravity-force-lab/issues/201#issuecomment-555773981

**Comment by jessegreenberg** [comment]
> I am also having a lot of trouble reading through the sim content with cursor gestures (up and down to go to headings; left and right to read line by line). It is easy for me to get skip sections or get stuck on elements.

Sorry if you are already aware of this, but there are different ways to scan content with the cursor. If you twist two fingers counterclockwise you can switch between reading lines, navigating buttons, navigating by heading, and so on. Is it possible it is stuck on "containers" setting instead of "lines"?

**Comment by terracoda** [comment]
@jessegreenberg, thanks for the tip. I can get the roter tool to pop-up and adjust, but it's a bit tricky.

**Comment by terracoda** [comment]
I am testing dev version 
https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.19/phet/gravity-force-lab_en_phet.html

and still having some trouble with the ruler interaction.

**Comment by zepumph** [comment]
In the above commits @jessegreenberg and I worked on this problem, as well as potentially a few other issues currently logged.

We found that the grab/drag interaction was very buggy, because the center point of the `ISLCRulerNode` (the node with the grad/drag interaction added to it), was not on top of the `RulerNode` child to the `ISLCObjectNode`, so the press wouldn't always "grab" the ruler. 

Here is @jessegreenberg's screen shot showing how the bounds of the ISLCRulerNode were larger than just the ruler itself.
![IMG_0016](https://user-images.githubusercontent.com/6856943/69586915-7fad6a00-0f90-11ea-8a25-268b01cadd3e.PNG)

The origin of the problem was that the ruler was `focusHighlightLayerable`, and so the focus highlight (including the "grab cue") was added as a child to the ISLCRulerNode.  You can see in the above picture how the bounds are wrapping the ruler and the space where the keyboard grab cue goes. 

We got rid of the focusHighlightLayerable feature, which was especially unnecessary since #104, and then we worked on the common code to make sure that Nodes that don't use `focusHighlightLayerable` still work with `GrabDragInteraction`. This involved updating `FocusHighlightPath` to manage a `transformSourceNode` optionally. Before this commit `FocusHighlightFromNode` was the only focus highlight type managing that.

@terracoda will you confirm this issue is fixed in the dev version I give to you later this evening?

**Comment by terracoda** [comment]
In https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.20/phet/gravity-force-lab_all_phet.html

Is getting released now. 
VO highlight follows ruler.
Bounds is snug around the ruler.

Once the ruler got a little difficult to grab and move from the top edge of the screen, but in general I think this is issue is resolved.

Nive work @jessegreenberg and @zepumph
