### ISSUE TITLE
Pink highlight on ruler layered over mass controls

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#224]
@zepumph, just noticed that the pink highlight comes on top of the mass controls. Hoping it is easy to put the highlight on the same z-index as the ruler itself.

![Screen Shot 2019-12-31 at 11 14 18 PM](https://user-images.githubusercontent.com/1902116/71637683-add33900-2c23-11ea-8800-4a45ee26c9c1.png)

![Screen Shot 2019-12-31 at 11 14 33 PM](https://user-images.githubusercontent.com/1902116/71637684-b3c91a00-2c23-11ea-8bcf-4a10e384504d.png)

**Comment by zepumph** [comment]
@terracoda would it be ok if it stayed the way it is? The reason why is because of the grab drag interaction cue. When we make it layerable, it surrounds the cue as well, and so this overlay issue is a byproduct of the solution for the weird VO highlight in the first screenshot in https://github.com/phetsims/gravity-force-lab/issues/205.

What do you think?

**Comment by terracoda** [comment]
It's fine by me.

**Comment by zepumph** [comment]
Thanks!
