### ISSUE TITLE
Should the keyboard nav dialog sections be consolidated

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#239]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/471
I noticed that the "grab ruler" action is separate from all the other ruler commands. I was told this was due to one being common code and the rest not being common code. However, from a user perspective, this doesn't make much sense and I think it would be more useful for the two sections to be combined.

**Visuals**
![whyseperate](https://user-images.githubusercontent.com/41024075/73407233-b5830d80-42b5-11ea-897e-06f7cca5cf47.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity Force Lab‬
URL: https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-rc.1/phet/gravity-force-lab_all_phet.html
Version: 2.2.0-rc.1 2020-01-28 03:08:20 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by zepumph** [comment]
@terracoda the reason these are both here is that the "Grab or Release Ruler" is a section that is general, and able to be added for any sim with a GrabDragInteraction.

I see three ways forward:
1. Keep it as it.
2. Remove the common code section and create a new and unit one each time
3. Try to coopt the common code one to include the custom section "Jump Or Move Grabbed Ruler".

If we go with three, I could experiment and let you know if it is even worth it. What do you think we should do @terracoda?

**Comment by terracoda** [comment]
@KatieWoe, good question. It is not about common code. It's about communicating a two-step interaction as clearly as possible.

We actually split the instructions because the interaction has two steps: a grab (or release) and a move. The headings are meant to communicate the two-step process without having to explicitly describe a two-step process, like:
**Ruler** 
- Step 1: Grab or Release Ruler with space or enter
- Step 2: Jump or Move Grabbed Ruler in several ways...

Technically, we could make the "Jump or Move Grabbed Ruler" section a subsection with a smaller heading but we have not done this for any other draggable objects (i.e. Balloons in BASE or Book in Friction). 

The Ruler interaction is our third grabble and draggable object, and we haven't had any complaints up to this point. What is different about the Ruler is that we emphasize the Jump shortcuts by putting them first before the moving instructions.

I think the instructions are clear and easy to grasp by a large range of readers. I strongly support keeping it as is, unless there is something about the instructions that is not clear.

**Comment by zepumph** [comment]
I think they are good the way they are. Thanks for the discussion.
