### ISSUE TITLE
Should ruler.opacityProperty be instrumented?

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-force-lab#271]
From https://github.com/phetsims/scenery/issues/1047, I noticed that the overrides files has:

```js
    "gravityForceLab.gravityForceLabScreen.view.ruler.opacityProperty": {
      "phetioFeatured": true
    },
```

In https://github.com/phetsims/scenery/issues/1047#issuecomment-708771210: 

> Add support for opacity. Here I'm tempted to not support default instrumentation at all, though I'm on the fence. Also perhaps a new issue to implement this? UPDATE: At today's meeting, @arouinfar indicated this may no longer be necessary. I suggested that if we need it for even one Node, we should add it centrally.

Tagging @zepumph so he is aware.

@arouinfar can you please comment?

**Comment by samreid** [comment]
I removed the override (temporarily?).  But if we add support for opacityProperty the same way we supported pickableProperty, it would be opt-in and automatically featured.

**Comment by arouinfar** [comment]
I was not involved in the phetioFeatured discussion for this sim. I think it was just @kathy-phet and @zepumph.

I image the ruler's opacityProperty was featured because we sometimes have transparent rulers, such as in Masses and Springs. In MAS, the opacity was reduced to better facilitate measurements.
![image](https://user-images.githubusercontent.com/8419308/96671416-e6f9a880-131e-11eb-8662-07802fba4d6b.png)

In Gravity Force Lab, the masses and ruler snap to an underlying grid and there are dashed lines which extend from the center of mass. I do not think a reduced opacity ruler significantly improves the UX and would really just be a aesthetic preference.

Personally, I do not think we need to opt-in to the opacityProperty here. @zepumph if that sounds reasonable to you, please close.

**Comment by samreid** [comment]
@zepumph and I discussed this, and agreed that we do not need an instrumented `opacityProperty` for this case.  Closing.
