### ISSUE TITLE
question about leaning behavior of the 'pullers'

### ISSUE THREAD

**Issue by jbphet** [phetsims/gravity-force-lab#50]
This sim has undergone some significant changes recently with respect to the range of masses that are supported.  The way that the puller figures lean has been tweaked a bit, but because the current calculation for the amount of leaning is linear, and the pullers go from upright to fully leaned over pretty quickly.  @aadish and I have made some adjustments, but we'd like to get feedback from the design team before we start generating release candidates.  @ariel-phet - can you take a look at the current master version and let us know if the behavior looks good?  If not, we may have to look at a more logarithmic mapping function.

**Comment by ariel-phet** [comment]
Current leaning behavior looks fine. The leaning behavior is a subtle cue anyhow, but good attention to detail @jbphet and @aadish. I think since we have the force vectors always active that is by far the more important representation, and in playing with several situations, the current leaning "feels" pretty good. Closing
