### ISSUE TITLE
Instrument sim for PhET-iO

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gravity-force-lab#76]
This sim is scheduled to be outfitted for PhET-iO by @jbphet after his work with States of Matter is finishing up.

@samreid will be available when @jbphet works on the sim and work through the instructions contained in the following file:

https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md

Part of the goal will be to refine this documentation

**Comment by samreid** [comment]
@jbphet can you speculate when we may begin working on this?

**Comment by jbphet** [comment]
We discussed my priorities in the 11/3/2016 status meeting, and once States of Matter is in RC phase I will start spending ~1day/week on this, so I suspect there will be some action on it next week or the week after.

**Comment by samreid** [comment]
On Thursday's status meeting, I suggested working on instrumenting Balloons and Static Electricity with @jbphet instead of Gravity Force Lab, in order to address https://github.com/phetsims/a11y-research/issues/2 and get "2 birds with one stone", but after review in phetsims/balloons-and-static-electricity#201 I discovered there is a lot of new code related to accessibility that would complicate the task, and that @jbphet and I should actually start with Gravity Force Lab, as originally planned.

So I'll create a new issue for step 1 of instrumentation, which is for code review.

**Comment by jbphet** [comment]
Below is the checklist of items that must be completed in order to implement the instrumention, extracted from https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md.  Refer back to the original document for explanations of the checklist items if needed.

- [ ] [Understand the goal](#understand-the-goal)
 - [ ] [Code review](#code-review)
 - [ ] [Import Tandem to main.js](#import-tandem-to-main.js)
 - [ ] [Create root tandem](#create-root-tandem)
 - [ ] [Pass tandems to sim screens](#pass-tandems-to-sim-screens)
 - [ ] [Pass tandems to model and view](#pass-tandems-to-model-and-view)
 - [ ] [Pass tandems to all constructors](#pass-tandems-to-all-constructors)
   + See also [Testing while adding Tandem instances](#testing-while-adding-tandem-instances). Test with `?phet-io.validateTandems=false` since common code components don't yet have tandems.
 - [ ] [Pass tandem instances to common code components](#pass-tandem-instances-to-common-code-components)
   + See also [Testing while adding Tandem instances](#testing-while-adding-tandem-instances).
 - [ ] [Replace types with tandemized equivalents](#replace-types-with-tandemized-equivalents)
 - [ ] [Instrument any Uninstrumented Common Code Components Used by the Sim](#instrument-any-uninstrumented-common-code-components-used-by-the-sim)
 - [ ] [Instrument new component types defined by the sim](#instrument-new-component-types-defined-by-the-sim)
 - [ ] [Add simulation specific support](#add-simulation-specific-support)
 - [ ] Are random numbers using `phet.joist.random`, and all doing so after modules are declared (non-statically)?  For
 instance, the following methods (and perhaps others) should not be used: `Math.random`, `_.shuffle`, `_.sample`, `_.random`
 - [ ] `undefined` values cannot be saved from the phet-io state save, sims should be written to use `null` instead.
 - [ ] Units in TNumber should be abbreviated, see https://github.com/phetsims/phet-io/issues/530
 - [ ] Update these instructions if you find them to be incomplete, inconsistent or incorrect.

**Comment by samreid** [comment]
@jbphet is taking the lead on this, I'll be supporting him with scheduled meetings.

**Comment by jbphet** [comment]
A test task has been created to test the result of this instrumentation effort, see https://github.com/phetsims/tasks/issues/743.  I'm going to unassign myself from this issue and link it to the test task.

**Comment by jbphet** [comment]
@samreid - this issue is old, but is assigned to me, and I'm not at all sure if this is done, still needed, or in general where it's at.  Do you have a sense, or can you assign to someone who does?  I'm certainly not spending any time on it at the moment and it's not on my radar for working on it anytime soon.

**Comment by samreid** [comment]
It looks like the PhET-iO instrumentation is pretty complete in the "instrument everything" approach, the next steps will be to:

1. Hold design meetings for PhET-iO API, and implement requested changes
2. QA Testing
3. Publish first PhET-iO version.

Assigned to @ariel-phet for priority and schedule.

**Comment by terracoda** [comment]
@jbphet, isn't this sim already outfitted for phet-io? 
Don't we need it to be outfitted in order to add sound?

**Comment by jbphet** [comment]
@terracoda - yes, phet-io was added, though from the sound of it, the job isn't 100% finished.  And no, it does not need to be outfitted with phet-io to add sound, we only use the phet-io capability when prototyping the sound design in phet-io wrappers.

**Comment by terracoda** [comment]
Thanks @jbphet!

**Comment by zepumph** [comment]
I took a first pass over the current implementation, and got rid of quite a few things. From here it would be good to have a design meeting. Notes and questions about current implementation:

* ISLCObjectNode's arrow node is not a child, but instead added as a node to the screen view, so visibility is toggled separately.
* We need a way potentially to have the label and label shadow node to keep in sync. 
* There is a new use case of a dynamic range passed to a NumberProperty, see https://github.com/phetsims/gravity-force-lab/issues/172
* I removed `minorTickLinesNode` and `majorTickLinesNode` from `RulerNode`, this may have been added to support the lab book wrapper (used in BLL), but I couldn't find any usages of them in the lab book repo. Does this sound like a good change 
* I removed `baseColorProperty` for the objects. It seems like if we want that instrumented perhaps we should add a color profile and handle it that way? I'm not sure.

**Comment by zepumph** [comment]
- [ ] enabledRangeProperty should be phetioReadonly
>I removed baseColorProperty for the objects. It seems like if we want that instrumented perhaps we should add a color profile and handle it that way? I'm not sure.

That's good! No need for it.

- [ ] Uninstrument the `ISLCObjectNode` why hide the mass Node slider?
- [ ] readonly `gravityForceLab.gravityForceLabScreen.view.mass1Node.forceArrowNode.arrowText.textProperty`

>We need a way potentially to have the label and label shadow node to keep in sync.

- [ ] Create composite instrumented label node that houses two uninstrumented texts (one for shadow and one for label). Keep the text editable.

>ISLCObjectNode's arrow node is not a child, but instead added as a node to the screen view, so visibility is toggled separately.

- [ ] Instrument the arrow itself (as `arrowNode` ) so we can hide that and keep the text. NOTE! This is actually instrumented, just not in this Node. It's in the screen view. We should change that Tandem hierarchy.
- [ ] rename `forceArrowNode` => `forceDisplayNode`
- [ ] rename `arrowText` to `forceText`


- [ ] this seems like a bug. You can execute actions from dragListeners, it would be nice to have a readonly function where you can add listener, but not execute actions.

- [ ] NEW ISSUE: NumberDisplay's  `valueNode` -> `valueText`, make it `phetioReadOnly`

>I removed minorTickLinesNode and majorTickLinesNode from RulerNode, this may have been added to support the lab book wrapper (used in BLL), but I couldn't find any usages of them in the lab book repo. Does this sound like a good change

- [ ] We didn't discuss this, though I don't want it to be lost.

**Comment by zepumph** [comment]
>this seems like a bug. You can execute actions from dragListeners, it would be nice to have a readonly function where you can add listener, but not execute actions.

After looking into phetioReadOnly events, I see that you can specify methods that can still be called when phetioReadOnly. EmitterIO.addListener is an example of one that can still be executed.

**Comment by zepumph** [comment]
Everything has been implemented. The last checkbox is to make sure to discuss the rulerNode updates I made.

**Comment by zepumph** [comment]
@kathy-phet and I continued going through Studio together.

- [ ] Investigate (22 minutes or less), hiding the dashed line when the forceDisplayNode is made invisible.
- [ ] Add a PhET-iO derived property for the distance between the two masses. This would have units. @arouinfar does `distanceProperty` sound alright with you?
- [ ] massControl1.titleNode should center better.
- [ ] revisit scientific notation checkbox and how it has a custom `enabledProperty` (which is the `showForceValuesProperty`). Do we really need that to be linked? @kathy-phet was interested in @arouinfar's opinion on that.

**Comment by zepumph** [comment]
> Investigate (22 minutes or less), hiding the dashed line when the forceDisplayNode is made invisible.

I think I will be able to do this by uninstrumenting ISLCForceArrowNode as the `forceDisplayNode`, and instead instrumented a new composite Node in ISLCObjectNode as `forceDisplayNode` that has ISLCForceArrowNode and the dashes as the child. This doesn't seem too bad to me.

**Comment by zepumph** [comment]
>Investigate (22 minutes or less), hiding the dashed line when the forceDisplayNode is made invisible.

It has been 20 minutes, and I found that things are further complicated because ISLCObjectNode.arrowNode isn't added as a child, but instead stored as a field, and added directly to the screen view (parent of the ISLCObjectNode). I am giving up on this. Sorry! Let me know if we want to investigate. I think I could make it work, but it would involve a fair bit of layout change.

**Comment by zepumph** [comment]
>Add a PhET-iO derived property for the distance between the two masses. This would have units. @arouinfar does distanceProperty sound alright with you?

How about "separationProperty" instead. Added above.

**Comment by zepumph** [comment]
More design meeting:

>revisit scientific notation checkbox and how it has a custom enabledProperty (which is the showForceValuesProperty). Do we really need that to be linked? @kathy-phet was interested in @arouinfar's opinion on that.

- [ ] `showForceValues` checkbox is no longer the `scientificNotationCheckbox's` `enabledProperty`

- [ ] instrument the vertical dashed line, to be able to be toggled, called `centerOfMassLineNode`

**Comment by zepumph** [comment]
Everything here has been completed. Now we will finish up over in https://github.com/phetsims/gravity-force-lab/issues/174. Closing
