### ISSUE TITLE
Add Scientific Notation checkbox

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-force-lab#94]
In today's design meeting for Coulomb's Law, we discussed adding a Scientific Notation option to Gravity Force Lab. Originally, the sim did not use scientific notation so that it would be more accessible to a younger audience. Given that there will be a Basics version, it seems appropriate to add a Scientific Notation checkbox to GFL.  

To accommodate the extra checkbox, we'll need to make a few layout tweaks, which I've mocked up:
![image](https://user-images.githubusercontent.com/8419308/29948938-c4fdac1e-8e6e-11e7-8367-c192c12ec76a.png)

Here are the changes overlaid on the published version:
![image](https://user-images.githubusercontent.com/8419308/29948954-d96aefae-8e6e-11e7-90d5-41f30d4f419e.png)

* Move ruler + masses up 40 px
* Maintain the same amount of spacing between the bottom of the checkbox panel and resetAllButton
* Reorder the checkboxes: Constant Radius, Show Values, Scientific Notation
* Move Mass panels up to remain top-aligned with checkbox panel

**Comment by arouinfar** [comment]
Just realized the mockups show all the checkboxes on. To clarify, only "Show Values" should be on by default.

**Comment by jessegreenberg** [comment]
Changes made above - the list in https://github.com/phetsims/gravity-force-lab/issues/94#issue-254493518 did not produce exactly what is shown on the mockup, presumably because of minor layout changes in the refactor to use inverse-square-law-common.

@arouinfar can you please take a look at master and see how things look? Mockup layout can be compared to current layout with query parameter ?showMockup. Please let me know if we should work on getting the layout more exactly in line with the mockup.

**Comment by arouinfar** [comment]
Looks great @jessegreenberg!! The mockup was meant as a guide, so no need to to make any further changes to the layout. 

Scientific notation doesn't appear to be working just yet, but I suppose you're probably still working on that. :)

**Comment by jessegreenberg** [comment]
> Scientific notation doesn't appear to be working just yet, but I suppose you're probably still working on that. 

Yikes, it was a moment ago sorry! Looking into it.

**Comment by jessegreenberg** [comment]
Should be working now @arouinfar.

**Comment by arouinfar** [comment]
👍
